connector.name=hive
hive.metastore.uri=thrift://hive-metastore:9083

# Garage (S3-compatible) holds the shared Parquet dataset -
fs.native-s3.enabled=true
s3.endpoint=http://garage:3900
s3.path-style-access=true
s3.aws-access-key=GK86b64fdb0310ad7397228be5
s3.aws-secret-key=4d1395f9529c8e8b9a7f61d1d31bf46714e30fa1a03ee1600c5b1ba599c131b2

# The Parquet directories are written by datagen/generate.py
hive.non-managed-table-writes-enabled=true
